/**
 * Per-sign confidence thresholds (Feature 2).
 *
 * GENERATED by `node scripts/evaluate.mjs --write-thresholds` — do not hand
 * edit values; re-run the script after recording sessions instead. Any sign
 * missing here falls back to CONFIDENCE_THRESHOLD (recognizer.js).
 *
 * Each value is the Youden-J-optimal cutoff separating that sign's correct
 * matches from wrong ones on real recorded data. Signs with thin data keep
 * the global default until more takes exist.
 */
export const SIGN_THRESHOLDS = {};

export const SIGN_THRESHOLD_META = {
  generatedAt: "2026-09-25T22:44:57.725Z",
  recordingCount: 3,
  globalFallback: 0.36,
};
