import os
import json
import asyncio
from utils.splitter import t5_translate
from routers.database import apply_hand_clearance_floor


def _serve_clear(frames):
    """Playback-time safety net: even if gloss_poses.json was generated by
    older code, no served frame may put a hand inside the torso/head, and the
    two palms may never overlap. Idempotent (floor-only), so re-running on
    already-fixed data is a no-op."""
    for f in frames:
        if not isinstance(f, dict) or "body" not in f:
            continue
        b = f.get("body") or {}
        lw = b.get("left_wrist")
        rw = b.get("right_wrist")
        lh = f.get("left_hand") or []
        rh = f.get("right_hand") or []
        if not isinstance(lh, list) or not isinstance(rh, list):
            continue
        lw, rw, lh, rh = apply_hand_clearance_floor(lw, rw, lh, rh)
        b["left_wrist"] = lw if lw else b.get("left_wrist")
        b["right_wrist"] = rw if rw else b.get("right_wrist")
    return frames
def load_json(path: str) -> dict:
    if os.path.exists(path):
        with open(path, "r") as f:
            try:
                return json.load(f)
            except json.JSONDecodeError:
                return {}
    else:
        with open(path, "w") as f:
            json.dump({}, f)
        return {}


# Initialize a bounded semaphore for T5 inference (1 concurrent request to prevent OOM/thrashing)
t5_semaphore = asyncio.BoundedSemaphore(1)

async def translate_and_generate_poses(text_chunk: str, translator):
    """
    Asynchronous generator that processes a text chunk, translates to gloss,
    looks up pre-recorded frames from the database, and yields payloads.
    """
    # Run the translation model inference with concurrency limit
    await t5_semaphore.acquire()
    async def _do_inference():
        try:
            return await asyncio.to_thread(t5_translate, text_chunk, translator)
        finally:
            t5_semaphore.release()
            
    worker = asyncio.create_task(_do_inference())
    gloss_text = await asyncio.shield(worker)
    gloss_text = gloss_text.strip()
    words = gloss_text.split()
    
    # Fallback: if T5 returns empty, use input directly
    if not words:
        words = text_chunk.strip().upper().split()
        
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    gloss_db = load_json(os.path.join(BASE_DIR, "gloss_poses.json"))
    fingerspell_db = load_json(os.path.join(BASE_DIR, "fingerspell_poses.json"))
    
    # Digits typed as numerals ("1", "23") must resolve to the recorded
    # number-word signs ("ONE", "TWO", "THREE"). Multi-digit numerals are
    # signed digit-by-digit, so "23" expands to TWO + THREE.
    DIGIT_WORDS = {
        "0": "ZERO", "1": "ONE", "2": "TWO", "3": "THREE", "4": "FOUR",
        "5": "FIVE", "6": "SIX", "7": "SEVEN", "8": "EIGHT", "9": "NINE",
    }

    expanded_words = []
    for word in words:
        clean = word.strip(".,!?\"'").upper()
        if not clean:
            continue
        if clean in gloss_db:
            expanded_words.append(clean)
        elif clean.isdigit() and all(ch in DIGIT_WORDS for ch in clean):
            # Pure numeral: digit-by-digit ("23" -> TWO, THREE). Any digit
            # without a recording falls through to the fingerspell path below.
            expanded_words.extend(DIGIT_WORDS[ch] for ch in clean)
        else:
            parts = clean.split("_")
            if len(parts) > 1 and all(p in gloss_db for p in parts):
                expanded_words.extend(parts)
            else:
                expanded_words.append(clean)
    
    for clean_word in expanded_words:
            
        # Path B: Database Match
        if clean_word in gloss_db:
            yield {
                "gloss_word": clean_word,
                "frames": _serve_clear(gloss_db[clean_word]),
                "duration_ms": 33,  # Strict 30FPS frame pacing
                "is_fingerspelling": False
            }
        else:
            # Fingerspelling Fallback
            print(f"Pose generation failed for '{clean_word}': Not in DB. Falling back to fingerspelling.")
            combined_frames = []
            
            for char in clean_word:
                if char in fingerspell_db and fingerspell_db[char]:
                    combined_frames.extend(fingerspell_db[char])
                else:
                    print(f"Warning: Character '{char}' not found in fingerspell_db. Skipping.")

            yield {
                "gloss_word": clean_word,
                "frames": combined_frames,
                "duration_ms": 33, # Strict 30FPS frame pacing
                "is_fingerspelling": True
            }
